#!/usr/bin/env bash
# strip-watermarks.sh — Remove AI attribution watermarks from git history
#
# Installs a global commit-msg hook that strips AI tool branding from
# every commit, and optionally rewrites existing history to clean old commits.
#
# Usage:
#   ./strip-watermarks.sh install   — install/update the global commit-msg hook
#   ./strip-watermarks.sh check     — audit current repo for watermarked commits
#   ./strip-watermarks.sh rewrite   — rewrite current branch to strip watermarks (DESTRUCTIVE)
#   ./strip-watermarks.sh status    — show hook installation status
set -euo pipefail

HOOKS_DIR="${GIT_GLOBAL_HOOKS:-$(git config --global core.hooksPath 2>/dev/null || echo "$HOME/.git-hooks")}"
HOOK_FILE="$HOOKS_DIR/commit-msg"

# Comprehensive watermark patterns (one per line, sed-ready)
WATERMARK_PATTERNS=(
    '/^Made-with: Cursor$/d'
    '/^Generated by Cursor$/d'
    '/^Generated with .*Claude/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Cc]ursor/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Gg][Pp][Tt]/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Gg]emini/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Cc]odeium/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Ww]indsurf/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Aa]nthrop/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Oo]pen[Aa][Ii]/d'
    '/^Co-[Aa]uthored-[Bb]y:.*[Gg]oogle/d'
    '/^Co-[Aa]uthored-[Bb]y:.*noreply@anthropic/d'
    '/^Signed-off-by:.*[Cc]laude/d'
    '/^Signed-off-by:.*[Cc]ursor/d'
    '/^Signed-off-by:.*[Cc]opilot/d'
    '/🤖 Generated with/d'
    '/^AI-Generated:/d'
)

# Grep patterns for auditing (extended regex)
GREP_PATTERN='(Made-with: Cursor|Generated by Cursor|Generated with .*Claude|Co-[Aa]uthored-[Bb]y:.*(Claude|Cursor|Copilot|GPT|Gemini|Codeium|Windsurf|Anthrop|OpenAI|Google|noreply@anthropic)|Signed-off-by:.*(Claude|Cursor|Copilot)|🤖 Generated with|^AI-Generated:)'

build_sed_args() {
    local args=""
    for p in "${WATERMARK_PATTERNS[@]}"; do
        args="$args -e '$p'"
    done
    echo "$args"
}

cmd_install() {
    echo "Installing watermark-stripping commit-msg hook..."
    echo "  hooks dir: $HOOKS_DIR"

    if [ -f "$HOOK_FILE" ]; then
        if grep -q "Strip AI watermarks" "$HOOK_FILE" 2>/dev/null; then
            echo "  hook already contains watermark stripping — updating patterns"
        else
            echo "  existing hook found — injecting watermark strip BEFORE existing content"
            local existing
            existing=$(cat "$HOOK_FILE")
        fi
    fi

    mkdir -p "$HOOKS_DIR"

    # Build the sed expression block
    local sed_block=""
    for p in "${WATERMARK_PATTERNS[@]}"; do
        sed_block="$sed_block    -e '$p' \\
"
    done

    cat > "$HOOK_FILE" << 'HOOKEOF'
#!/usr/bin/env bash
# ── Strip AI watermarks ──────────────────────────────────────
# Auto-managed by strip-watermarks.sh. Covers:
# Cursor, Claude, Copilot, GPT, Gemini, Codeium, Windsurf, etc.
if [ -f "$1" ]; then
  sed -i '' \
    -e '/^Made-with: Cursor$/d' \
    -e '/^Generated by Cursor$/d' \
    -e '/^Generated with .*Claude/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]ursor/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Gg][Pp][Tt]/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Gg]emini/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]odeium/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Ww]indsurf/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Aa]nthrop/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Oo]pen[Aa][Ii]/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Gg]oogle/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*noreply@anthropic/d' \
    -e '/^Signed-off-by:.*[Cc]laude/d' \
    -e '/^Signed-off-by:.*[Cc]ursor/d' \
    -e '/^Signed-off-by:.*[Cc]opilot/d' \
    -e '/🤖 Generated with/d' \
    -e '/^AI-Generated:/d' \
    "$1"
  # Remove trailing blank lines left after stripping
  sed -i '' -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$1"
fi

# Chain to repo-local hook if it exists
_repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || _repo_root=""
if [ -n "$_repo_root" ]; then
  _local_hook="$_repo_root/.git/hooks/commit-msg"
  if [ -x "$_local_hook" ] && [ ! "$_local_hook" -ef "$0" ]; then
    "$_local_hook" "$@"
  fi
fi
HOOKEOF

    chmod +x "$HOOK_FILE"

    # Ensure global hooksPath is set
    local current_path
    current_path=$(git config --global core.hooksPath 2>/dev/null || true)
    if [ "$current_path" != "$HOOKS_DIR" ]; then
        echo "  NOTE: core.hooksPath is '$current_path', not '$HOOKS_DIR'"
        echo "  Run: git config --global core.hooksPath '$HOOKS_DIR'"
    fi

    echo "  done. All future commits will be scrubbed."
}

cmd_check() {
    echo "Auditing commits for AI watermarks..."
    echo ""

    local count=0
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "  $line"
            count=$((count + 1))
        fi
    done < <(git log --all --format="%H %ai %s" --grep="Made-with: Cursor" 2>/dev/null)
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "  $line"
            count=$((count + 1))
        fi
    done < <(git log --all --format="%H %ai %s" --grep="Co-Authored-By: Claude" 2>/dev/null)
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "  $line"
            count=$((count + 1))
        fi
    done < <(git log --all --format="%H %ai %s" --grep="Generated with" 2>/dev/null)
    while IFS= read -r line; do
        if [ -n "$line" ]; then
            echo "  $line"
            count=$((count + 1))
        fi
    done < <(git log --all --format="%H %ai %s" --grep="Generated by Cursor" 2>/dev/null)

    echo ""
    if [ "$count" -eq 0 ]; then
        echo "Clean. No AI watermarks found."
    else
        echo "Found $count watermarked commit(s)."
        echo "Run '$0 rewrite' to clean them (DESTRUCTIVE — rewrites history)."
    fi
}

cmd_rewrite() {
    echo "WARNING: This rewrites git history. Only use on branches not yet shared."
    echo "Press Ctrl+C to abort, or Enter to continue..."
    read -r

    echo "Creating safety tag: pre-watermark-strip-$(date +%Y%m%d-%H%M%S)"
    git tag "pre-watermark-strip-$(date +%Y%m%d-%H%M%S)"

    git filter-branch --force --msg-filter '
        sed \
            -e "/^Made-with: Cursor$/d" \
            -e "/^Generated by Cursor$/d" \
            -e "/^Generated with .*Claude/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Cc]ursor/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Gg][Pp][Tt]/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Gg]emini/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Cc]odeium/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Ww]indsurf/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Aa]nthrop/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Oo]pen[Aa][Ii]/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*[Gg]oogle/d" \
            -e "/^Co-[Aa]uthored-[Bb]y:.*noreply@anthropic/d" \
            -e "/^Signed-off-by:.*[Cc]laude/d" \
            -e "/^Signed-off-by:.*[Cc]ursor/d" \
            -e "/^Signed-off-by:.*[Cc]opilot/d" \
            -e "/🤖 Generated with/d" \
            -e "/^AI-Generated:/d" \
        | sed -e :a -e "/^\n*$/{\\$d;N;ba" -e "}"
    ' -- --all

    echo ""
    echo "History rewritten. Verify with: $0 check"
    echo "Safety tag created for rollback if needed."
}

cmd_status() {
    echo "=== Watermark Hook Status ==="
    echo ""
    echo "Global hooks path: $(git config --global core.hooksPath 2>/dev/null || echo '(not set)')"
    echo "Expected hook:     $HOOK_FILE"

    if [ -f "$HOOK_FILE" ]; then
        if grep -q "Strip AI watermarks" "$HOOK_FILE" 2>/dev/null; then
            echo "Status:            ACTIVE"
        else
            echo "Status:            HOOK EXISTS but no watermark stripping"
        fi
    else
        echo "Status:            NOT INSTALLED"
    fi

    echo ""
    echo "Covered tools: Cursor, Claude, Copilot, GPT, Gemini, Codeium, Windsurf, Anthropic, OpenAI, Google"
}

case "${1:-status}" in
    install) cmd_install ;;
    check)   cmd_check ;;
    rewrite) cmd_rewrite ;;
    status)  cmd_status ;;
    *)
        echo "Usage: $0 {install|check|rewrite|status}"
        exit 1
        ;;
esac
