#!/usr/bin/env bash
# strip-watermarks.sh — Remove AI tool attribution from git commits
#
# A universal, public-use script that strips branding trailers, co-author
# lines, and watermarks injected by AI coding assistants into git commit
# messages. Works on macOS and Linux.
#
# Covered tools (as of 2026-04):
#   IDEs & Editors:       Cursor, Windsurf, Trae, Zed AI, Void, Positron
#   Agents (terminal):    Claude Code, Aider, OpenAI Codex CLI, Gemini CLI,
#                         Kimi CLI, Qwen Code, opencode, Goose, Mistral Vibe
#   Agents (cloud):       GitHub Copilot, Devin, Augment, Amp, Cody
#   Extensions:           Cline, Roo Code, Continue, Supermaven, Tabnine,
#                         Blackbox AI, Pieces, Qodo (CodiumAI)
#   Platforms:            Replit, Bolt.new, Lovable, v0 (Vercel)
#   JetBrains:            JetBrains AI Assistant, Junie
#   Cloud providers:      Amazon Q / CodeWhisperer, Google Gemini Code Assist
#
# Usage:
#   ./strip-watermarks.sh install   — install global commit-msg hook
#   ./strip-watermarks.sh check     — audit repo for watermarked commits
#   ./strip-watermarks.sh rewrite   — rewrite branch history (DESTRUCTIVE)
#   ./strip-watermarks.sh status    — show hook state
#   ./strip-watermarks.sh test      — run self-test with sample messages
#
# Requirements: bash 4+, sed, git
# License: MIT — https://opensource.org/licenses/MIT
set -euo pipefail

# ── Configuration ─────────────────────────────────────────────

# Where to install the hook. Respects GIT_GLOBAL_HOOKS env override.
HOOKS_DIR="${GIT_GLOBAL_HOOKS:-$(git config --global core.hooksPath 2>/dev/null || echo "$HOME/.git-hooks")}"
HOOK_FILE="$HOOKS_DIR/commit-msg"

# sed -i portability: macOS needs '', GNU doesn't
if sed --version 2>/dev/null | grep -q GNU; then
    SED_INPLACE=(sed -i)
else
    SED_INPLACE=(sed -i '')
fi

# ── Watermark Patterns ───────────────────────────────────────
#
# Each pattern is a sed delete command. Grouped by category.
# To add a new tool, append a pattern and update the header comment.

generate_sed_args() {
    cat << 'PATTERNS'
# --- Cursor ---
/^Made-with: Cursor$/d
/^Generated by Cursor$/d
/^Made-with: Cursor Agent$/d

# --- Claude Code / Anthropic ---
/^Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d
/^Co-[Aa]uthored-[Bb]y:.*[Aa]nthrop/d
/^Co-[Aa]uthored-[Bb]y:.*noreply@anthropic/d
/^Signed-off-by:.*[Cc]laude/d
/^Signed-off-by:.*noreply@anthropic/d
/^Generated with .*[Cc]laude/d
/🤖 Generated with \[Claude Code\]/d
/🤖 Generated with Claude Code/d

# --- GitHub Copilot ---
/^Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d
/^Co-[Aa]uthored-[Bb]y:.*copilot\[bot\]/d
/^Co-[Aa]uthored-[Bb]y:.*noreply@github\.com/d
/^Signed-off-by:.*[Cc]opilot/d
/^Generated-by: GitHub Copilot/d

# --- OpenAI Codex CLI ---
/^Co-[Aa]uthored-[Bb]y:.*[Cc]odex/d
/^Co-[Aa]uthored-[Bb]y:.*codex@openai\.com/d
/^Co-[Aa]uthored-[Bb]y:.*noreply@openai\.com/d
/^Generated-by:.*[Cc]odex/d

# --- Aider ---
/^Co-[Aa]uthored-[Bb]y:.*aider/d
/^Co-[Aa]uthored-[Bb]y:.*noreply@aider\.chat/d

# --- Google (Gemini CLI, Gemini Code Assist, Jules) ---
/^Co-[Aa]uthored-[Bb]y:.*[Gg]emini/d
/^Co-[Aa]uthored-[Bb]y:.*[Gg]oogle/d
/^Co-[Aa]uthored-[Bb]y:.*[Jj]ules/d
/^Generated-by:.*[Gg]emini/d

# --- Amazon Q / CodeWhisperer ---
/^Co-[Aa]uthored-[Bb]y:.*[Aa]mazon Q/d
/^Co-[Aa]uthored-[Bb]y:.*[Cc]ode[Ww]hisperer/d
/^Co-[Aa]uthored-[Bb]y:.*amazon\.com/d
/^Generated-by:.*Amazon/d

# --- Windsurf / Codeium ---
/^Co-[Aa]uthored-[Bb]y:.*[Ww]indsurf/d
/^Co-[Aa]uthored-[Bb]y:.*[Cc]odeium/d
/^Made-with: Windsurf$/d
/^Generated-by:.*Windsurf/d
/^Generated-by:.*Codeium/d

# --- JetBrains (AI Assistant, Junie) ---
/^Co-[Aa]uthored-[Bb]y:.*[Jj]unie/d
/^Co-[Aa]uthored-[Bb]y:.*[Jj]et[Bb]rains/d
/^Co-[Aa]uthored-[Bb]y:.*noreply@jetbrains\.com/d
/^Generated-by:.*JetBrains/d
/^Generated-by:.*Junie/d

# --- Trae (ByteDance) ---
/^Co-[Aa]uthored-[Bb]y:.*[Tt]rae/d
/^Made-with: Trae$/d

# --- Cline / Roo Code ---
/^Co-[Aa]uthored-[Bb]y:.*[Cc]line/d
/^Co-[Aa]uthored-[Bb]y:.*[Rr]oo.Code/d
/^Co-[Aa]uthored-[Bb]y:.*[Rr]oo.Cline/d

# --- Continue.dev ---
/^Co-[Aa]uthored-[Bb]y:.*[Cc]ontinue/d

# --- Devin ---
/^Co-[Aa]uthored-[Bb]y:.*[Dd]evin/d
/^Co-[Aa]uthored-[Bb]y:.*devin-ai/d
/^Co-[Aa]uthored-[Bb]y:.*cognition\.ai/d

# --- Augment ---
/^Co-[Aa]uthored-[Bb]y:.*[Aa]ugment/d

# --- Amp (Sourcegraph) ---
/^Co-[Aa]uthored-[Bb]y:.*[Aa]mp/d
/^Co-[Aa]uthored-[Bb]y:.*[Ss]ourcegraph/d
/^Co-[Aa]uthored-[Bb]y:.*[Cc]ody/d

# --- Tabnine ---
/^Co-[Aa]uthored-[Bb]y:.*[Tt]abnine/d

# --- Supermaven ---
/^Co-[Aa]uthored-[Bb]y:.*[Ss]upermaven/d

# --- Qodo (formerly CodiumAI) ---
/^Co-[Aa]uthored-[Bb]y:.*[Qq]odo/d
/^Co-[Aa]uthored-[Bb]y:.*[Cc]odium[Aa][Ii]/d

# --- Blackbox AI ---
/^Co-[Aa]uthored-[Bb]y:.*[Bb]lack[Bb]ox/d

# --- Pieces ---
/^Co-[Aa]uthored-[Bb]y:.*[Pp]ieces/d

# --- Replit ---
/^Co-[Aa]uthored-[Bb]y:.*[Rr]eplit/d
/^Generated-by:.*Replit/d

# --- Bolt / Lovable / v0 ---
/^Co-[Aa]uthored-[Bb]y:.*[Bb]olt/d
/^Co-[Aa]uthored-[Bb]y:.*[Ll]ovable/d
/^Co-[Aa]uthored-[Bb]y:.*v0/d
/^Generated-by:.*Bolt/d
/^Generated-by:.*Lovable/d

# --- OpenHands / Goose / Mistral Vibe ---
/^Co-[Aa]uthored-[Bb]y:.*[Oo]pen[Hh]ands/d
/^Co-[Aa]uthored-[Bb]y:.*[Gg]oose/d
/^Co-[Aa]uthored-[Bb]y:.*[Mm]istral/d

# --- Kimi CLI / Qwen Code ---
/^Co-[Aa]uthored-[Bb]y:.*[Kk]imi/d
/^Co-[Aa]uthored-[Bb]y:.*[Qq]wen/d
/^Co-[Aa]uthored-[Bb]y:.*[Mm]oonshot/d

# --- Zed AI ---
/^Co-[Aa]uthored-[Bb]y:.*[Zz]ed/d

# --- opencode ---
/^Co-[Aa]uthored-[Bb]y:.*opencode/d

# --- Generic catch-all patterns ---
/^AI-Generated:/d
/^Generated-by: AI$/d
/^Assisted-by: AI$/d
/^Generated-by:.*[Aa]ssistant$/d
PATTERNS
}

# Grep pattern for auditing (extended regex, used by cmd_check)
GREP_PATTERNS=(
    "Made-with: Cursor"
    "Generated by Cursor"
    "Generated with.*Claude"
    "Co-[Aa]uthored-[Bb]y:.*(Claude|Cursor|Copilot|Codex|Gemini|Google|Aider|Windsurf|Codeium|Junie|JetBrains|Trae|Cline|Roo.Code|Devin|Augment|Amp|Sourcegraph|Cody|Tabnine|Supermaven|Qodo|CodiumAI|BlackBox|Pieces|Replit|Bolt|Lovable|v0|OpenHands|Goose|Mistral|Kimi|Qwen|Moonshot|Zed|opencode|Continue|Amazon|noreply@)"
    "Signed-off-by:.*(Claude|Cursor|Copilot|anthropic)"
    "Generated-by:.*(Cursor|Copilot|Codex|Gemini|JetBrains|Junie|Windsurf|Codeium|Amazon|Replit|Bolt|Lovable|AI$)"
    "AI-Generated:"
    "Assisted-by: AI"
    "🤖 Generated with"
)

# ── Hook Content ─────────────────────────────────────────────
# This function writes the hook as a self-contained portable script.

write_hook() {
    local target="$1"
    cat > "$target" << 'HOOKEOF'
#!/usr/bin/env bash
# commit-msg hook: strip AI coding tool watermarks
# Auto-generated by strip-watermarks.sh
# https://github.com/Lyther/Coding-Agent-Prompts
#
# Portable: works on macOS (BSD sed) and Linux (GNU sed).
# To update patterns, re-run: strip-watermarks.sh install

if [ ! -f "$1" ]; then
    exit 0
fi

# Detect sed -i syntax
if sed --version 2>/dev/null | grep -q GNU; then
    _sedi() { sed -i "$@"; }
else
    _sedi() { sed -i '' "$@"; }
fi

_sedi \
    -e '/^Made-with: Cursor$/d' \
    -e '/^Made-with: Cursor Agent$/d' \
    -e '/^Made-with: Windsurf$/d' \
    -e '/^Made-with: Trae$/d' \
    -e '/^Generated by Cursor$/d' \
    -e '/^Generated with .*[Cc]laude/d' \
    -e '/🤖 Generated with/d' \
    -e '/^Generated-by:.*[Cc]opilot/d' \
    -e '/^Generated-by:.*[Cc]odex/d' \
    -e '/^Generated-by:.*[Gg]emini/d' \
    -e '/^Generated-by:.*JetBrains/d' \
    -e '/^Generated-by:.*Junie/d' \
    -e '/^Generated-by:.*Windsurf/d' \
    -e '/^Generated-by:.*Codeium/d' \
    -e '/^Generated-by:.*Amazon/d' \
    -e '/^Generated-by:.*Replit/d' \
    -e '/^Generated-by:.*Bolt/d' \
    -e '/^Generated-by:.*Lovable/d' \
    -e '/^Generated-by: AI$/d' \
    -e '/^Assisted-by: AI$/d' \
    -e '/^Generated-by:.*[Aa]ssistant$/d' \
    -e '/^AI-Generated:/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Aa]nthrop/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*copilot\[bot\]/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]odex/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Gg]emini/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Gg]oogle/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Jj]ules/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Aa]mazon/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]ode[Ww]hisperer/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Ww]indsurf/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]odeium/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Jj]unie/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Jj]et[Bb]rains/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Tt]rae/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]line/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Rr]oo.Code/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Rr]oo.Cline/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]ontinue/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Dd]evin/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*cognition\.ai/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Aa]ugment/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Ss]ourcegraph/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]ody/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Tt]abnine/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Ss]upermaven/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Qq]odo/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Cc]odium[Aa][Ii]/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Bb]lack[Bb]ox/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Pp]ieces/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Rr]eplit/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Bb]olt/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Ll]ovable/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Oo]pen[Hh]ands/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Gg]oose/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Mm]istral/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Kk]imi/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Qq]wen/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Mm]oonshot/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Zz]ed/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*opencode/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Aa]ider/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*aider\.chat/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*[Aa]mp\b/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*v0\b/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*noreply@anthropic/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*noreply@github\.com/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*noreply@openai\.com/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*noreply@jetbrains\.com/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*codex@openai\.com/d' \
    -e '/^Co-[Aa]uthored-[Bb]y:.*amazon\.com/d' \
    -e '/^Signed-off-by:.*[Cc]laude/d' \
    -e '/^Signed-off-by:.*[Cc]ursor/d' \
    -e '/^Signed-off-by:.*[Cc]opilot/d' \
    -e '/^Signed-off-by:.*noreply@anthropic/d' \
    "$1"

# Remove trailing blank lines
_sedi -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$1"

# Chain to repo-local hook if present
_repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || _repo_root=""
if [ -n "$_repo_root" ]; then
    _local_hook="$_repo_root/.git/hooks/commit-msg"
    if [ -x "$_local_hook" ] && [ ! "$_local_hook" -ef "$0" ]; then
        "$_local_hook" "$@"
    fi
fi
HOOKEOF
    chmod +x "$target"
}

# ── Commands ──────────────────────────────────────────────────

cmd_install() {
    echo "Installing watermark-stripping commit-msg hook..."
    echo "  target: $HOOK_FILE"

    mkdir -p "$HOOKS_DIR"

    if [ -f "$HOOK_FILE" ]; then
        if grep -q "strip-watermarks" "$HOOK_FILE" 2>/dev/null; then
            echo "  hook exists — updating patterns in place"
        else
            # Preserve existing hook by appending chain
            echo "  existing hook found — backing up to $HOOK_FILE.bak"
            cp "$HOOK_FILE" "$HOOK_FILE.bak"
        fi
    fi

    write_hook "$HOOK_FILE"

    # Verify global hooksPath
    local current_path
    current_path=$(git config --global core.hooksPath 2>/dev/null || true)
    if [ -z "$current_path" ]; then
        echo ""
        echo "  NOTE: core.hooksPath not set. To activate globally, run:"
        echo "    git config --global core.hooksPath '$HOOKS_DIR'"
    elif [ "$current_path" != "$HOOKS_DIR" ]; then
        echo ""
        echo "  NOTE: core.hooksPath is '$current_path' (expected '$HOOKS_DIR')"
        echo "  The hook was written to $HOOK_FILE but may not be active."
    fi

    echo ""
    echo "  done. Future commits will be scrubbed across all repos."
    echo ""
    echo "  Covered tools ($(echo "${GREP_PATTERNS[@]}" | tr '|' '\n' | wc -l | tr -d ' ')+ patterns):"
    echo "    Cursor, Claude Code, GitHub Copilot, OpenAI Codex CLI, Aider,"
    echo "    Gemini CLI/Code Assist, Amazon Q, Windsurf, Codeium, JetBrains/Junie,"
    echo "    Trae, Cline, Roo Code, Continue, Devin, Augment, Amp, Sourcegraph/Cody,"
    echo "    Tabnine, Supermaven, Qodo, Blackbox AI, Pieces, Replit, Bolt, Lovable,"
    echo "    v0, OpenHands, Goose, Mistral Vibe, Kimi CLI, Qwen Code, Zed AI, opencode"
}

cmd_check() {
    echo "Auditing commits for AI watermarks..."
    echo ""

    local total=0
    local seen_hashes=""

    for pattern in "${GREP_PATTERNS[@]}"; do
        while IFS= read -r line; do
            [ -z "$line" ] && continue
            local hash="${line%% *}"
            # Deduplicate
            if echo "$seen_hashes" | grep -qF "$hash"; then
                continue
            fi
            seen_hashes="$seen_hashes $hash"
            echo "  $line"
            total=$((total + 1))
        done < <(git log --all --extended-regexp --format="%H %ai %s" --grep="$pattern" 2>/dev/null)
    done

    echo ""
    if [ "$total" -eq 0 ]; then
        echo "Clean. No AI watermarks found."
    else
        echo "Found $total watermarked commit(s)."
        echo "Run '$0 rewrite' to clean them (DESTRUCTIVE — rewrites history)."
    fi
}

cmd_rewrite() {
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║  WARNING: This rewrites git history using filter-branch.   ║"
    echo "║  Only use on branches NOT pushed to a shared remote.       ║"
    echo "║  A safety tag will be created for rollback.                ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "Press Enter to continue, Ctrl+C to abort..."
    read -r

    local tag="pre-watermark-strip-$(date +%Y%m%d-%H%M%S)"
    echo "Creating safety tag: $tag"
    git tag "$tag"

    # Build the sed command from generate_sed_args, stripping comments
    local sed_script
    sed_script=$(generate_sed_args | grep -v '^#' | grep -v '^$' | tr '\n' ';')

    git filter-branch --force --msg-filter "
        sed $(generate_sed_args | grep -v '^#' | grep -v '^$' | sed \"s|^|-e '|;s|$|'|\" | tr '\n' ' ') \
        | sed -e :a -e '/^\n*\$/{\$d;N;ba' -e '}'
    " -- --all

    echo ""
    echo "History rewritten. Verify with: $0 check"
    echo "Rollback with: git reset --hard $tag"
}

cmd_status() {
    echo "=== AI Watermark Hook Status ==="
    echo ""
    echo "Global hooks path: $(git config --global core.hooksPath 2>/dev/null || echo '(not set)')"
    echo "Expected hook:     $HOOK_FILE"

    if [ -f "$HOOK_FILE" ]; then
        if grep -q "strip-watermarks\|Strip AI watermarks" "$HOOK_FILE" 2>/dev/null; then
            echo "Status:            ACTIVE"
            local pattern_count
            pattern_count=$(grep -c "^    -e " "$HOOK_FILE" 2>/dev/null || echo 0)
            echo "Patterns:          $pattern_count sed rules"
        else
            echo "Status:            HOOK EXISTS (no watermark stripping detected)"
        fi
    else
        echo "Status:            NOT INSTALLED"
        echo ""
        echo "Run '$0 install' to set up."
    fi

    echo ""
    echo "Covered: Cursor, Claude Code, Copilot, Codex CLI, Aider, Gemini,"
    echo "  Amazon Q, Windsurf, Codeium, JetBrains, Junie, Trae, Cline,"
    echo "  Roo Code, Continue, Devin, Augment, Amp, Cody, Tabnine,"
    echo "  Supermaven, Qodo, Blackbox, Pieces, Replit, Bolt, Lovable,"
    echo "  v0, OpenHands, Goose, Mistral, Kimi, Qwen, Zed, opencode"
}

cmd_test() {
    echo "=== Self-test: verifying watermark stripping ==="
    echo ""

    local pass=0
    local fail=0
    local tmpdir
    tmpdir=$(mktemp -d)

    run_test() {
        local name="$1"
        local input="$2"
        local expected="$3"

        local tmpfile="$tmpdir/msg"
        printf '%s\n' "$input" > "$tmpfile"

        # Simulate the hook's sed commands using write_hook output
        local hook="$tmpdir/hook"
        write_hook "$hook"
        bash "$hook" "$tmpfile"

        local actual
        actual=$(cat "$tmpfile")

        if [ "$actual" = "$expected" ]; then
            echo "  PASS  $name"
            pass=$((pass + 1))
        else
            echo "  FAIL  $name"
            echo "    expected: $(echo "$expected" | head -1)"
            echo "    got:      $(echo "$actual" | head -1)"
            fail=$((fail + 1))
        fi
    }

    run_test "Cursor trailer" \
        "$(printf 'fix(auth): validate JWT\n\nMade-with: Cursor')" \
        "fix(auth): validate JWT"

    run_test "Claude co-author" \
        "$(printf 'feat(api): add endpoint\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>')" \
        "feat(api): add endpoint"

    run_test "Aider co-author" \
        "$(printf 'refactor: clean up\n\nCo-authored-by: aider (gpt-4o) <noreply@aider.chat>')" \
        "refactor: clean up"

    run_test "Copilot co-author" \
        "$(printf 'fix: null check\n\nCo-Authored-By: copilot[bot] <noreply@github.com>')" \
        "fix: null check"

    run_test "Codex CLI co-author" \
        "$(printf 'feat: new feature\n\nCo-Authored-By: Codex <codex@openai.com>')" \
        "feat: new feature"

    run_test "Gemini co-author" \
        "$(printf 'docs: update readme\n\nCo-Authored-By: Gemini <noreply@google.com>')" \
        "docs: update readme"

    run_test "Claude Code emoji" \
        "$(printf 'feat: something\n\n🤖 Generated with [Claude Code](https://claude.ai/code)')" \
        "feat: something"

    run_test "Devin co-author" \
        "$(printf 'fix: bug\n\nCo-Authored-By: Devin <devin@cognition.ai>')" \
        "fix: bug"

    run_test "Junie co-author" \
        "$(printf 'chore: deps\n\nCo-Authored-By: Junie <noreply@jetbrains.com>')" \
        "chore: deps"

    run_test "Multiple watermarks" \
        "$(printf 'fix: thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nMade-with: Cursor\n🤖 Generated with Claude Code')" \
        "fix: thing"

    run_test "Clean message preserved" \
        "$(printf 'feat(core): real human commit\n\nThis was written by a human.')" \
        "$(printf 'feat(core): real human commit\n\nThis was written by a human.')"

    run_test "Windsurf trailer" \
        "$(printf 'fix: style\n\nMade-with: Windsurf')" \
        "fix: style"

    run_test "Generated-by Codex" \
        "$(printf 'feat: init\n\nGenerated-by: Codex CLI')" \
        "feat: init"

    run_test "Amazon Q co-author" \
        "$(printf 'fix: lambda\n\nCo-Authored-By: Amazon Q <noreply@amazon.com>')" \
        "fix: lambda"

    rm -rf "$tmpdir"

    echo ""
    echo "Results: $pass passed, $fail failed"
    [ "$fail" -eq 0 ] && return 0 || return 1
}

# ── Entrypoint ────────────────────────────────────────────────

case "${1:-status}" in
    install) cmd_install ;;
    check)   cmd_check ;;
    rewrite) cmd_rewrite ;;
    status)  cmd_status ;;
    test)    cmd_test ;;
    -h|--help|help)
        echo "Usage: $0 {install|check|rewrite|status|test}"
        echo ""
        echo "  install  — Install/update global commit-msg hook"
        echo "  check    — Audit current repo for watermarked commits"
        echo "  rewrite  — Rewrite branch history to strip watermarks (DESTRUCTIVE)"
        echo "  status   — Show hook installation status"
        echo "  test     — Run self-test with sample commit messages"
        ;;
    *)
        echo "Unknown command: $1"
        echo "Usage: $0 {install|check|rewrite|status|test}"
        exit 1
        ;;
esac
