name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea1f5d1d24d8927480e995a5a8e45e72974 # v4.4.0
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run check
      - run: npm run check:commands
      - run: npm run check:generated
      - run: npm run check:rules
      - run: npm test
      - run: npm run build -- --target all
      - run: npm pack --dry-run --json
